### ISSUE TITLE
Issues with haxe 4 preview 5

### ISSUE THREAD

**Issue by Hersir88** [massiveinteractive/msignal#22]
Hi,
got errors with haxe 4 preview 5.
`msignal/1,2,4/msignal/SlotList.hx:80: characters 2-42 : length: Custom property accessor is no longer supported, please use get`

`msignal/1,2,4/msignal/Slot.hx:50: characters 2-55 : listener: Custom property accessor is no longer supported, please use set`

**Comment by elsassph** [comment]
Fixed in msignal 1.2.5
